image: registry.3pjgames.com/docker/build-env:pandoc

stages:
  - build
  - deploy

build-html:
  stage: build
  script:
    - make html
  artifacts:
    name: html
    paths:
      - index.html
      - timerange.png
      - pandoc.css
  only:
    - master
  tags:
    - docker

build-docx:
  stage: build
  script:
    - make docx
  artifacts:
    name: docx
    paths:
      - 日志规范.docx
  only:
    - master
  tags:
    - docker


deploy:
  stage: deploy
  script:
    - tar -cf - index.html pandoc.css *.png *.docx | ssh assets@nas.3pjgames.com "mkdir -p public/xi/logs-convention && tar -xf - -C public/xi/logs-convention"
  dependencies:
    - build-html
    - build-docx
  only:
    - master
  tags:
    - deploy
  environment:
    name: doc
    url: https://svn.3pjgames.com/assets/public/xi/logs-convention/
